const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path');
const { ClipboardHistory, classify } = require('../src/clipboard');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'clip-'));
let text = '', img = null;
const fake = { availableFormats: () => (img ? ['image/png'] : ['text/plain']), readText: () => text, readImage: () => img, writeText: (t) => { text = t; img = null; }, writeImage: () => {} };
const h = new ClipboardHistory(dir, fake, { max: 3 });
text = 'https://medsystem.eng.br'; h.poll(); assert.strictEqual(h.items.length, 1); assert.strictEqual(h.items[0].kind, 'url');
h.poll(); assert.strictEqual(h.items.length, 1, 'mesmo conteúdo não duplica');
text = 'const x = 1;\nconsole.log(x);'; h.poll(); assert.strictEqual(h.items[0].kind, 'code');
text = '#ff9f0a'; h.poll(); text = '(11) 99999-0000'; h.poll();
assert.strictEqual(h.items.length, 3, 'limite max'); assert.ok(!h.items.some((i) => i.kind === 'url'), 'mais antigo saiu');
h.pin(h.items[2].id, true); text = 'novo'; h.poll(); assert.strictEqual(h.items.filter((i) => i.pinned).length, 1, 'fixado sobrevive ao limite');
const codeItem = h.items.find((i) => i.kind === 'code') || h.items[1];
assert.ok(h.use(h.items[1].id)); assert.strictEqual(text, h.items[0].text, 'use recoloca e vai para o topo');
h.poll(); assert.strictEqual(h.items.filter((i) => i.hash === h.items[0].hash).length, 1, 'recolocar não cria entrada nova');
img = { isEmpty: () => false, toPNG: () => Buffer.from('png-bytes'), getSize: () => ({ width: 10, height: 20 }) }; h.poll();
assert.strictEqual(h.items[0].type, 'image'); assert.ok(h.items[0].data.startsWith('data:image/png;base64,')); assert.strictEqual(h.list()[0].w, 10);
const h2 = new ClipboardHistory(dir, fake); assert.strictEqual(h2.items.length, h.items.length, 'persistido');
h.clear(true); assert.ok(h.items.every((i) => i.pinned)); h.clear(false); assert.strictEqual(h.items.length, 0);
assert.strictEqual(classify('joao@medsystem.eng.br'), 'email'); assert.strictEqual(classify('C:\\Users\\ti'), 'path'); assert.strictEqual(classify('1234.5'), 'number'); assert.strictEqual(classify('oi tudo bem'), 'text');
console.log('clipboard OK');
