const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sidenotch', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getVersion: () => ipcRenderer.invoke('app:version'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  refresh: () => ipcRenderer.invoke('usage:refresh'),
  getDisplays: () => ipcRenderer.invoke('displays:get'),
  setIgnoreMouse: (v) => ipcRenderer.send('bar:ignore-mouse', v),
  setBarHeight: (h) => ipcRenderer.send('bar:height', h),
  setFocusable: (v) => ipcRenderer.send('bar:focusable', v),
  drag: (phase) => ipcRenderer.send('bar:drag', phase),
  openSettings: () => ipcRenderer.send('app:open-settings'),
  openUrl: (u) => ipcRenderer.send('app:open-url', u),
  quit: () => ipcRenderer.send('app:quit'),
  getApprovals: () => ipcRenderer.invoke('approvals:get'),
  decide: (id, decision, extra) => ipcRenderer.invoke('approvals:decide', id, decision, extra || {}),
  installHook: () => ipcRenderer.invoke('approvals:install-hook'),
  uninstallHook: () => ipcRenderer.invoke('approvals:uninstall-hook'),
  dismiss: (id) => ipcRenderer.invoke('feed:dismiss', id),
  maestriPair: (opts) => ipcRenderer.invoke('maestri:pair', opts),
  maestriUnpair: () => ipcRenderer.invoke('maestri:unpair'),
  maestriAction: (id, action, text) => ipcRenderer.invoke('maestri:action', id, action, text),
  setDnd: (v) => ipcRenderer.invoke('dnd:set', v),
  getUpdate: () => ipcRenderer.invoke('update:get'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  getSystem: () => ipcRenderer.invoke('system:get'),
  media: (cmd) => ipcRenderer.invoke('media:cmd', cmd),
  listApps: (opts) => ipcRenderer.invoke('apps:list', opts),
  launchApp: (id) => ipcRenderer.invoke('apps:launch', id),
  listWebApps: () => ipcRenderer.invoke('webapps:list'),
  openWebApp: (id) => ipcRenderer.invoke('webapps:open', id),
  setWebApps: (list) => ipcRenderer.invoke('webapps:set', list),
  getCalendar: () => ipcRenderer.invoke('calendar:get'),
  getWeather: () => ipcRenderer.invoke('weather:get'),
  onWeather: (cb) => ipcRenderer.on('weather', (_e, d) => cb(d)),
  refreshCalendar: () => ipcRenderer.invoke('calendar:refresh'),
  getDocs: () => ipcRenderer.invoke('docs:get'),
  setDocs: (patch) => ipcRenderer.invoke('docs:set', patch),
  onSystem: (cb) => ipcRenderer.on('system', (_e, d) => cb(d)),
  onCalendar: (cb) => ipcRenderer.on('calendar', (_e, d) => cb(d)),
  onApprovals: (cb) => ipcRenderer.on('approvals', (_e, d) => cb(d)),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, d) => cb(d)),
  onUpdate: (cb) => ipcRenderer.on('update', (_e, d) => cb(d)),
  onUsage: (cb) => ipcRenderer.on('usage', (_e, d) => cb(d)),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, d) => cb(d)),
  hubGet: () => ipcRenderer.invoke('hub:get'),
  hubLogin: (email, password) => ipcRenderer.invoke('hub:login', email, password),
  hubLogout: () => ipcRenderer.invoke('hub:logout'),
  hubSync: () => ipcRenderer.invoke('hub:sync'),
  hubRead: (id) => ipcRenderer.invoke('hub:read', id),
  hubTask: (id, status) => ipcRenderer.invoke('hub:task', id, status),
  hubOpen: (link, notifId) => ipcRenderer.invoke('hub:open', link, notifId),
  hubCheckPath: (p) => ipcRenderer.invoke('hub:check-path', p),
  hubCreateTask: (t) => ipcRenderer.invoke('hub:create-task', t),
  soundTest: (preset, cfg) => ipcRenderer.invoke('sound:test', preset, cfg),
  soundPick: () => ipcRenderer.invoke('sound:pick'),
  onSound: (cb) => ipcRenderer.on('sound:play', (_e, d) => cb(d)),
  clipList: () => ipcRenderer.invoke('clipboard:list'),
  clipUse: (id) => ipcRenderer.invoke('clipboard:use', id),
  clipPin: (id, v) => ipcRenderer.invoke('clipboard:pin', id, v),
  clipRemove: (id) => ipcRenderer.invoke('clipboard:remove', id),
  clipClear: (keep) => ipcRenderer.invoke('clipboard:clear', keep),
  onClipboard: (cb) => ipcRenderer.on('clipboard', (_e, d) => cb(d)),
  qaSelectDone: (r) => ipcRenderer.invoke('qa:select-done', r),
  qaSelectCancel: () => ipcRenderer.send('qa:select-cancel'),
  qaInteractive: (on) => ipcRenderer.send('qa:interactive', !!on),
  qaDrag: (id) => ipcRenderer.send('qa:drag', id),
  qaStackEmpty: () => ipcRenderer.send('qa:stack-empty'),
  qaCopy: (id) => ipcRenderer.invoke('qa:copy', id),
  qaSave: (id) => ipcRenderer.invoke('qa:save', id),
  qaUpload: (id) => ipcRenderer.invoke('qa:upload', id),
  qaOcr: (id) => ipcRenderer.invoke('qa:ocr', id),
  qaPin: (id, v) => ipcRenderer.invoke('qa:pin', id, v),
  qaEdit: (id) => ipcRenderer.invoke('qa:edit', id),
  qaList: () => ipcRenderer.invoke('qa:list'),
  qaSearch: (q) => ipcRenderer.invoke('qa:search', q),
  qaRemove: (id) => ipcRenderer.invoke('qa:remove', id),
  qaRestore: (id) => ipcRenderer.invoke('qa:restore', id),
  qaCapture: () => ipcRenderer.invoke('qa:capture'),
  qaOpenFile: (id) => ipcRenderer.invoke('qa:open-file', id),
  qaEditorLoad: (id) => ipcRenderer.invoke('qa:editor-load', id),
  qaEditorSave: (id, shapes, png) => ipcRenderer.invoke('qa:editor-save', id, shapes, png),
  onQa: (cb) => { for (const ev of ['config', 'push', 'update']) ipcRenderer.on('qa:' + ev, (_e, d) => cb(ev, d)); },
  onCaptures: (cb) => ipcRenderer.on('captures', (_e, d) => cb(d)),
  onHub: (cb) => ipcRenderer.on('hub', (_e, d) => cb(d)),
  onNotchOpen: (cb) => ipcRenderer.on('notch:open', (_e, t) => cb(t)),
  onBar: (cb) => { for (const ch of ['bar:open', 'bar:toggle', 'bar:blur']) ipcRenderer.on(ch, () => cb(ch.split(':')[1])); }
});
