const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('sidenotch', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getVersion: () => ipcRenderer.invoke('app:version'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  refresh: () => ipcRenderer.invoke('usage:refresh'),
  getDisplays: () => ipcRenderer.invoke('displays:get'),
  setIgnoreMouse: (v) => ipcRenderer.send('bar:ignore-mouse', v),
  notchHot: (r) => ipcRenderer.send('notch:hot', r),
  setBarHeight: (h) => ipcRenderer.send('bar:height', h),
  setFocusable: (v) => ipcRenderer.send('bar:focusable', v),
  winCtl: (a) => ipcRenderer.send('win:ctl', a),
  onWinState: (cb) => ipcRenderer.on('win:state', (_e, st) => cb(st)),
  drag: (phase) => ipcRenderer.send('bar:drag', phase),
  openSettings: () => ipcRenderer.send('app:open-settings'),
  openUrl: (u) => ipcRenderer.send('app:open-url', u),
  quit: () => ipcRenderer.send('app:quit'),
  getApprovals: () => ipcRenderer.invoke('approvals:get'),
  decide: (id, decision, extra) => ipcRenderer.invoke('approvals:decide', id, decision, extra || {}),
  installHook: () => ipcRenderer.invoke('approvals:install-hook'),
  uninstallHook: () => ipcRenderer.invoke('approvals:uninstall-hook'),
  dismiss: (id) => ipcRenderer.invoke('feed:dismiss', id),
  maestriPair: (opts) => ipcRenderer.invoke('maestri:pair', opts),
  maestriUnpair: () => ipcRenderer.invoke('maestri:unpair'),
  maestriAction: (id, action, text) => ipcRenderer.invoke('maestri:action', id, action, text),
  setDnd: (v) => ipcRenderer.invoke('dnd:set', v),
  getUpdate: () => ipcRenderer.invoke('update:get'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  getSystem: () => ipcRenderer.invoke('system:get'),
  media: (cmd) => ipcRenderer.invoke('media:cmd', cmd),
  listApps: (opts) => ipcRenderer.invoke('apps:list', opts),
  launchApp: (id) => ipcRenderer.invoke('apps:launch', id),
  listWebApps: () => ipcRenderer.invoke('webapps:list'),
  openWebApp: (id) => ipcRenderer.invoke('webapps:open', id),
  setWebApps: (list) => ipcRenderer.invoke('webapps:set', list),
  getCalendar: () => ipcRenderer.invoke('calendar:get'),
  getWeather: () => ipcRenderer.invoke('weather:get'),
  onWeather: (cb) => ipcRenderer.on('weather', (_e, d) => cb(d)),
  refreshCalendar: () => ipcRenderer.invoke('calendar:refresh'),
  getDocs: () => ipcRenderer.invoke('docs:get'),
  setDocs: (patch) => ipcRenderer.invoke('docs:set', patch),
  onSystem: (cb) => ipcRenderer.on('system', (_e, d) => cb(d)),
  onCalendar: (cb) => ipcRenderer.on('calendar', (_e, d) => cb(d)),
  onApprovals: (cb) => ipcRenderer.on('approvals', (_e, d) => cb(d)),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, d) => cb(d)),
  onUpdate: (cb) => ipcRenderer.on('update', (_e, d) => cb(d)),
  onUsage: (cb) => ipcRenderer.on('usage', (_e, d) => cb(d)),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, d) => cb(d)),
  hubGet: () => ipcRenderer.invoke('hub:get'),
  hubLogin: (email, password) => ipcRenderer.invoke('hub:login', email, password),
  hubLogout: () => ipcRenderer.invoke('hub:logout'),
  hubSync: () => ipcRenderer.invoke('hub:sync'),
  hubRead: (id) => ipcRenderer.invoke('hub:read', id),
  hubTask: (id, status) => ipcRenderer.invoke('hub:task', id, status),
  hubOpen: (link, notifId) => ipcRenderer.invoke('hub:open', link, notifId),
  hubCheckPath: (p) => ipcRenderer.invoke('hub:check-path', p),
  hubCreateTask: (t) => ipcRenderer.invoke('hub:create-task', t),
  soundTest: (preset, cfg) => ipcRenderer.invoke('sound:test', preset, cfg),
  soundPick: () => ipcRenderer.invoke('sound:pick'),
  onSound: (cb) => ipcRenderer.on('sound:play', (_e, d) => cb(d)),
  clipList: () => ipcRenderer.invoke('clipboard:list'),
  clipUse: (id) => ipcRenderer.invoke('clipboard:use', id),
  clipPin: (id, v) => ipcRenderer.invoke('clipboard:pin', id, v),
  clipRemove: (id) => ipcRenderer.invoke('clipboard:remove', id),
  clipClear: (keep) => ipcRenderer.invoke('clipboard:clear', keep),
  onClipboard: (cb) => ipcRenderer.on('clipboard', (_e, d) => cb(d)),
  qaSelectDone: (r) => ipcRenderer.invoke('qa:select-done', r),
  qaSelectCancel: () => ipcRenderer.send('qa:select-cancel'),
  qaInteractive: (on) => ipcRenderer.send('qa:interactive', !!on),
  qaSize: (h) => ipcRenderer.send('qa:size', h),
  // foco (pomodoro)
  focusGet: () => ipcRenderer.invoke('focus:get'),
  focusStart: (t) => ipcRenderer.invoke('focus:start', t),
  focusToggle: (t) => ipcRenderer.invoke('focus:toggle', t),
  focusPause: () => ipcRenderer.invoke('focus:pause'),
  focusStop: () => ipcRenderer.invoke('focus:stop'),
  focusComplete: (id, kind) => ipcRenderer.invoke('focus:complete', id, kind),
  focusRefresh: () => ipcRenderer.invoke('focus:refresh'),
  hubTaskEstimate: (id, min) => ipcRenderer.invoke('hub:task-estimate', id, min),
  hubTaskUpdate: (id, patch) => ipcRenderer.invoke('hub:task-update', id, patch),
  hubTaskDelete: (id) => ipcRenderer.invoke('hub:task-delete', id),
  openTasks: () => ipcRenderer.invoke('tasks:open'),
  // quadro de Sistemas
  boardOpen: () => ipcRenderer.invoke('board:open'),
  boardGet: (force) => ipcRenderer.invoke('board:get', force),
  boardFeed: (n) => ipcRenderer.invoke('board:feed', n),
  boardAlerts: () => ipcRenderer.invoke('board:alerts'),
  boardTake: (id, startDev) => ipcRenderer.invoke('board:take', id, startDev),
  boardMove: (id, status, motivo) => ipcRenderer.invoke('board:move', id, status, motivo),
  boardBlock: (id, on, motivo) => ipcRenderer.invoke('board:block', id, on, motivo),
  boardBrief: (kind) => ipcRenderer.invoke('board:brief', kind),
  boardAssign: (id, userId, startDev) => ipcRenderer.invoke('board:assign', id, userId, startDev),
  boardCard: (id) => ipcRenderer.invoke('board:card', id),
  boardPeople: (force) => ipcRenderer.invoke('board:people', force),
  // bandeja de arquivos
  // pausa do café
  coffeeGet: () => ipcRenderer.invoke('coffee:get'),
  coffeeToggle: (p, l) => ipcRenderer.invoke('coffee:toggle', p, l),
  coffeeStart: (p, l) => ipcRenderer.invoke('coffee:start', p, l),
  coffeeStop: (p) => ipcRenderer.invoke('coffee:stop', p),
  coffeeCancel: (p) => ipcRenderer.invoke('coffee:cancel', p),
  coffeeRefresh: () => ipcRenderer.invoke('coffee:refresh'),
  onCoffee: (cb) => ipcRenderer.on('coffee', (_e, st) => cb(st)),
  filesList: () => ipcRenderer.invoke('files:list'),
  filesAdd: (paths) => ipcRenderer.invoke('files:add', paths),
  filesPick: () => ipcRenderer.invoke('files:pick'),
  filesRemove: (id) => ipcRenderer.invoke('files:remove', id),
  filesClear: () => ipcRenderer.invoke('files:clear'),
  filesPin: (id) => ipcRenderer.invoke('files:pin', id),
  filesOpen: (id) => ipcRenderer.invoke('files:open', id),
  filesReveal: (id) => ipcRenderer.invoke('files:reveal', id),
  filesLink: (id) => ipcRenderer.invoke('files:link', id),
  filesDrag: (id) => ipcRenderer.send('files:drag', id),
  // Electron 32 tirou File.path; o caminho real do arquivo solto vem daqui
  pathForFile: (f) => { try { return webUtils.getPathForFile(f); } catch { return (f && f.path) || ''; } },
  dropMode: (on) => ipcRenderer.send('files:drop-mode', !!on),
  onDropMode: (cb) => ipcRenderer.on('files:drop-mode', (_e, on) => cb(on)),
  onFiles: (cb) => ipcRenderer.on('files', (_e, l) => cb(l)),
  // comandos do TI
  cmdList: () => ipcRenderer.invoke('cmd:list'),
  cmdRun: (id) => ipcRenderer.invoke('cmd:run', id),
  cmdDefaults: () => ipcRenderer.invoke('cmd:defaults'),
  // linguagem natural e resposta de WhatsApp
  nlpParse: (t) => ipcRenderer.invoke('nlp:parse', t),
  hubChatSend: (convId, text) => ipcRenderer.invoke('hub:chat-send', convId, text),
  onFocus: (cb) => ipcRenderer.on('focus', (_e, st) => cb(st)),
  qaDrag: (id) => ipcRenderer.send('qa:drag', id),
  qaStackEmpty: () => ipcRenderer.send('qa:stack-empty'),
  qaCopy: (id) => ipcRenderer.invoke('qa:copy', id),
  qaSave: (id) => ipcRenderer.invoke('qa:save', id),
  qaUpload: (id) => ipcRenderer.invoke('qa:upload', id),
  qaOcr: (id) => ipcRenderer.invoke('qa:ocr', id),
  qaPin: (id, v) => ipcRenderer.invoke('qa:pin', id, v),
  qaEdit: (id) => ipcRenderer.invoke('qa:edit', id),
  qaList: () => ipcRenderer.invoke('qa:list'),
  qaSearch: (q) => ipcRenderer.invoke('qa:search', q),
  qaRemove: (id) => ipcRenderer.invoke('qa:remove', id),
  qaRestore: (id) => ipcRenderer.invoke('qa:restore', id),
  qaCapture: () => ipcRenderer.invoke('qa:capture'),
  qaOpenFile: (id) => ipcRenderer.invoke('qa:open-file', id),
  qaEditorLoad: (id) => ipcRenderer.invoke('qa:editor-load', id),
  qaEditorSave: (id, shapes, png) => ipcRenderer.invoke('qa:editor-save', id, shapes, png),
  onQa: (cb) => { for (const ev of ['config', 'push', 'update', 'remove']) ipcRenderer.on('qa:' + ev, (_e, d) => cb(ev, d)); },
  qaLog: (m) => ipcRenderer.send('qa:log', String(m)),
  onCaptures: (cb) => ipcRenderer.on('captures', (_e, d) => cb(d)),
  onHub: (cb) => ipcRenderer.on('hub', (_e, d) => cb(d)),
  onNotchOpen: (cb) => ipcRenderer.on('notch:open', (_e, t) => cb(t)),
  onBar: (cb) => { for (const ch of ['bar:open', 'bar:toggle', 'bar:blur']) ipcRenderer.on(ch, () => cb(ch.split(':')[1])); }
});
